[package]
name = "llm-stream-map"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1.89"
either = { version = "1.16.0", features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
itertools = "0.15.0"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
reqwest-sse = "0.2.0"
schemars = { version = "1.2.1", features = ["indexmap2", "preserve_order"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["preserve_order"] }
stefans-utils = { version = "0.12.0", features = ["secret-serialize-redacted"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["full"] }
url = { version = "2" }
